# This file contains all the secrets for the server and client in order to manage and
# secure all of them in the same place. In Kubernetes, this file will be mapped to
# Secrets and all other config files will be mapped to mapConfig

---

# Sever section

# Key store password, the path of keystore is defined in server.yml
serverKeystorePass: ${secret.serverKeystorePass:password}

# Key password, the key is in keystore
serverKeyPass: ${secret.serverKeyPass:password}

# Trust store password, the path of truststore is defined in server.yml
serverTruststorePass: ${secret.serverTruststorePass:password}


# Client section

# Key store password, the path of keystore is defined in server.yml
clientKeystorePass: ${secret.clientKeystorePass:password}

# Key password, the key is in keystore
clientKeyPass: ${secret.clientKeyPass:password}

# Trust store password, the path of truststore is defined in server.yml
clientTruststorePass: ${secret.clientTruststorePass:password}

# Authorization code client secret for OAuth2 server
authorizationCodeClientSecret: ${secret.authorizationCodeClientSecret:f6h1FTI8Q3-7UScPZDzfXA}

# Client credentials client secret for OAuth2 server
clientCredentialsClientSecret: ${secret.clientCredentialsClientSecret:f6h1FTI8Q3-7UScPZDzfXA}

# Fresh token client secret for OAuth2 server
refreshTokenClientSecret: ${secret.refreshTokenClientSecret:f6h1FTI8Q3-7UScPZDzfXA}

# Key distribution client secret for OAuth2 server
keyClientSecret: ${secret.keyClientSecret:f6h1FTI8Q3-7UScPZDzfXA}

# SQL Server Password
sqlServerPassword: ${secret.sqlServerPassword:change-me}

# dbPassword: CRYPT:MHLp4zqPgyPTQPMU1mBWihFFzoDXimsCXF9GlO55BMo=
dbPassword: mysqlpw

# htPassword: password for the embedded database
h2Password: sa

# Mysql Password
mysqlPassword: ${secret.mysqlPassword:mysqlPassword}

# Maria Password
mariaPassword: ${secret.oraclePassword:mariaPassword}

# Postgres Password
postgresPassword:  ${secret.postgresPassword:postgresPassword}

# SQL Server Password

# Oracle Password
oraclePassword: ${secret.oraclePassword:change-me}
# Consul service registry and discovery

# Consul Token for service registry and discovery
# consulToken: the_one_ring
consulToken: ${secret.consulToken:consulToken}

# EmailSender password
emailPassword: ${secret.emailPassword:change-to-real-password}
