
# Server configuration
---
# This is the default binding address if the service is dockerized.
ip: ${server.ip:0.0.0.0}

# Http port if enableHttp is true. It will be ignored if dynamicPort is true.
httpPort: ${server.httpPort:8089}

# Enable HTTP should be false by default. It should be only used for testing with clients or tools
# that don't support https or very hard to import the certificate. Otherwise, https should be used.
# When enableHttp, you must set enableHttps to false, otherwise, this flag will be ignored. There is
# only one protocol will be used for the server at anytime. If both http and https are true, only
# https listener will be created and the server will bind to https port only.
enableHttp: ${server.enableHttp:true}

# Https port if enableHttps is true. It will be ignored if dynamicPort is true.
httpsPort: ${server.httpsPort:8843}

# Enable HTTPS should be true on official environment and most dev environments.
enableHttps: ${server.enableHttps:false}

# Http/2 is enabled by default for better performance and it works with the client module
enableHttp2: ${server.enableHttp2:false}


# Keystore file name in config folder. KeystorePass is in secret.yml to access it.
#keystoreName: ${server.keystoreName:server.keystore}

# Flag that indicate if two way TLS is enabled. Not recommended in docker container.
enableTwoWayTls: ${server.enableTwoWayTls:false}

# Truststore file name in config folder. TruststorePass is in secret.yml to access it.
#truststoreName: ${server.truststoreName:server.truststore}

# Unique service identifier. Used in service registration and discovery etc.
serviceId: ${server.serviceId:light-schedule-template.1.00}

# Flag to enable self service registration. This should be turned on on official test and production. And
# dyanmicPort should be enabled if any orchestration tool is used like Kubernetes.
enableRegistry: ${server.enableRegistry:false}


# environment tag that will be registered on consul to support multiple instances per env for testing.
# https://github.com/networknt/light-doc/blob/master/docs/content/design/env-segregation.md
# This tag should only be set for testing env, not production. The production certification process will enforce it.
# environment: test1

# Build Number
# Allows teams to audit the value and set it according to their release management processes
buildNumber: ${server.buildNumber:1.00}
