#--------------------------------------------------------------------------------
# service.yml
#--------------------------------------------------------------------------------
service.singletons:
  - com.networknt.utility.Decryptor:
      - com.networknt.decrypt.AESDecryptor

  - com.networknt.db.GenericDataSource:
      - com.networknt.db.H2DataSource:
          - java.lang.String: H2DataSource


  - com.networknt.eventuate.jdbc.EventuateSchema:
      - com.networknt.eventuate.jdbc.EventuateSchema:
          - java.lang.String: none

  - com.networknt.tram.cdc.polling.connector.MessagePollingDataProvider:
      - com.networknt.tram.cdc.polling.connector.MessagePollingDataProvider

  - com.networknt.eventuate.server.common.PublishingStrategy:
      - com.mservicetech.schedule.publisher.MileStonePublishingStrategy

  - com.mservicetech.schedule.publisher.CdcPublisher:
      - com.mservicetech.schedule.publisher.LocalCdcLogPublisher
  # HandlerProvider implementation
  - com.networknt.handler.HandlerProvider:
      - com.mservicetech.schedule.CdcServer
  # StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.StartupHookProvider:
      - com.mservicetech.schedule.CdcServerStartupHookProvider
  # ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
  - com.networknt.server.ShutdownHookProvider:
      - com.mservicetech.schedule.CdcServerShutdownHookProvider
# MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.


#--------------------------------------------------------------------------------
# datasource.yml
#--------------------------------------------------------------------------------
datasource.H2DataSource:
  DriverClassName: org.h2.jdbcx.JdbcDataSource
  jdbcUrl: jdbc:h2:mem:XE;MODE=MYSQL;INIT=runscript from 'classpath:script/cdc_ddl.sql'\;
  username: sa
  maximumPoolSize: 2
  connectionTimeout: 500
